apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-cluster-role-binding
  namespace: geepht
subjects:
  - kind: ServiceAccount
    name: github-actions-service-account
    namespace: geepht
roleRef:
  kind: ClusterRole
  name: github-actions-cluster-role
  apiGroup: rbac.authorization.k8s.io
