name: Build and Deploy Application to Production

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-push-container-image-to-dockerhub:
    uses: ./.github/workflows/build-and-push-container-image-to-dockerhub.yml
    with:
      docker_image: codeywilliams/geepht
      image_tags: latest
      dockerfile: ./Dockerfile
      docker_context: .
      secrets: inherit
#
# deploy-production-app:
#   needs: build-and-publish-image-to-dockerhub
#   uses: ./.github/workflows/deploy-kubernetes-resources.yml
