name: Deploy to Kubernetes
on:
  workflow_call:
    secrets:
      BASE_64_KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.BASE_64_KUBE_CONFIG }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gettext
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Run rails migrations
        if: success()
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          envsubst < k8s/app/rails_migration_job_template.yaml | kubectl apply -f -
          kubectl wait --for=condition=complete --timeout=180s job/migrate-${GITHUB_SHA}

      - name: Process manifest templates
        env:
          GITHUB_SHA: ${{ github.sha }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          envsubst < ./k8s/app/deployment_template.yaml > ./k8s/app/deployment.yaml
          envsubst < ./k8s/app/kustomization_template.yaml > ./k8s/app/kustomization.yaml

      - name: Apply Kustomize file
        if: success()
        run: kubectl apply -k ./k8s/app
